import { describe, it, expect } from 'vitest'
import { getProjectSessionKey } from '../../src/main/session-path'

describe('getProjectSessionKey', () => {
  // Golden fixtures: verified against real ~/.claude/projects/ directory names
  // generated by Claude CLI on Windows

  it('encodes a Windows path with drive letter', () => {
    expect(getProjectSessionKey('C:\\Users\\lfrmo\\Documents\\clui-cc-windows'))
      .toBe('C--Users-lfrmo-Documents-clui-cc-windows')
  })

  it('encodes a Windows path with different drive', () => {
    expect(getProjectSessionKey('D:\\projects\\my-app'))
      .toBe('D--projects-my-app')
  })

  it('encodes a POSIX path', () => {
    expect(getProjectSessionKey('/Users/lfrmo/Documents/clui-cc'))
      .toBe('-Users-lfrmo-Documents-clui-cc')
  })

  it('encodes a path with spaces', () => {
    expect(getProjectSessionKey('C:\\Users\\lfrmo\\Documents\\my project'))
      .toBe('C--Users-lfrmo-Documents-my project')
  })

  it('encodes a path with mixed separators', () => {
    expect(getProjectSessionKey('C:\\Users\\lfrmo/Documents/project'))
      .toBe('C--Users-lfrmo-Documents-project')
  })

  it('encodes a Windows home directory', () => {
    expect(getProjectSessionKey('C:\\Users\\lfrmo'))
      .toBe('C--Users-lfrmo')
  })

  it('encodes a root POSIX path', () => {
    expect(getProjectSessionKey('/'))
      .toBe('-')
  })

  it('handles path with trailing separator', () => {
    // Trailing slash becomes trailing dash
    expect(getProjectSessionKey('C:\\Users\\lfrmo\\'))
      .toBe('C--Users-lfrmo-')
  })

  it('handles UNC path', () => {
    // \\server\share -> --server-share
    expect(getProjectSessionKey('\\\\server\\share\\project'))
      .toBe('--server-share-project')
  })

  it('handles path with unicode characters', () => {
    expect(getProjectSessionKey('C:\\Users\\lfrmo\\Documents\\проект'))
      .toBe('C--Users-lfrmo-Documents-проект')
  })

  it('does not collapse consecutive dashes', () => {
    // C:\ -> C-- (colon becomes dash, backslash becomes dash = two dashes)
    const result = getProjectSessionKey('C:\\test')
    expect(result).toBe('C--test')
    expect(result).toContain('--')
  })
})
